### ISSUE TITLE
Issue Inserting Documents

### ISSUE THREAD

**Issue by elithrar** [dancannon/gorethink#42]
I have a struct that has an Insert() method on it and am passing a populated reference to the struct to Insert. Inside Insert, I set some timestamps, generate a base64 encoded string for use as an "edit URL", and so on.
- The program is panicking when it hits the `doc, err := gorethink.Table("demo").Insert(l).RunWrite(conn)` line.
- I've ripped this out into a quick demo application and have replicated it. I'm running the latest head of gorethink and RethinkDB 1.10.1. Dan's example program works fine.
- I'm using struct tags to ignore some fields but removing those didn't change anything.

Here's the relevant application code (the rest is just the struct definition and a quick main() setting the string fields to dummy values):

``` go
var conn *gorethink.Session

func (l *Listing) Insert() error {

    l.PostedDate = time.Now()
    l.EditedDate, l.RenewedDate = l.PostedDate, l.PostedDate
    l.Active = true

    editID, err := GetEditKey(32)
    if err != nil {
        return err
    }
    l.EditID = base64.URLEncoding.EncodeToString(editID)

    log.Printf("Prior to insert: %#v \n", l)

    doc, err := gorethink.Table("listings").Insert(l).RunWrite(conn)
    if err != nil {
        return err
    }

    if doc.Created != 1 {
        return errors.New("The document was not inserted correctly: " + l.Title + l.RepEmail)
    }

    l.Id = doc.GeneratedKeys[0]

    log.Printf("inserted id: %q", l.Id)
    return nil
}

func init() {
    conn, err := gorethink.Connect(map[string]interface{}{
        "address":  "localhost:28015",
        "database": "demo",
    })
    if err != nil {
        log.Fatalln(err.Error())
    }

    fmt.Printf("RethinkDB connection: %v\n", conn)
}
```

The program panics on line 78 — the insert statement:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4fcf6]

goroutine 1 [running]:
runtime.panic(0x1b7860, 0x439319)
        /usr/local/Cellar/go/1.2rc3/libexec/src/pkg/runtime/panic.c:266 +0xb6
github.com/dancannon/gorethink.(*Session).nextToken(0x0, 0x0)
        /Users/matt/.go/src/github.com/dancannon/gorethink/session.go:159 +0x46
github.com/dancannon/gorethink.(*Session).startQuery(0x0, 0x1ec6d0, 0x6, 0x38, 0x0, ...)
        /Users/matt/.go/src/github.com/dancannon/gorethink/session.go:165 +0x5e
github.com/dancannon/gorethink.RqlTerm.Run(0x1ec6d0, 0x6, 0x38, 0x0, 0x0, ...)
        /Users/matt/.go/src/github.com/dancannon/gorethink/query.go:124 +0x104
github.com/dancannon/gorethink.RqlTerm.RunRow(0x1ec6d0, 0x6, 0x38, 0x0, 0x0, ...)
        /Users/matt/.go/src/github.com/dancannon/gorethink/query.go:142 +0x9f
github.com/dancannon/gorethink.RqlTerm.RunWrite(0x1ec6d0, 0x6, 0x38, 0x0, 0x0, ...)
        /Users/matt/.go/src/github.com/dancannon/gorethink/query.go:162 +0x92
main.(*Listing).Insert(0xc21004a6e0, 0xc21004a6e0, 0xc210085080)
        /Users/matt/Desktop/editurl.go:78 +0x2c2
main.main()
        /Users/matt/Desktop/editurl.go:57 +0x16e
exit status 2
``
```

**Comment by elithrar** [comment]
Stupidly enough, I was overwriting the global `conn` variable inside `init`, instead of `var err error` and then `conn, err = <connection>` instead.

(long day!)
