### ISSUE TITLE
"duplicate enum registered: VersionDummy_Version" In init() chain

### ISSUE THREAD

**Issue by wildattire** [dancannon/gorethink#54]
We're trying to migrate from rethinkgo to gorethink, but we can't even so much as get past the init() chain to _use_ the library. Panic and trace follows.

panic: proto: duplicate enum registered: VersionDummy_Version

goroutine 1 [running]:
runtime.panic(0x3c3440, 0xc2100c8340)
    /usr/local/Cellar/go/1.2/libexec/src/pkg/runtime/panic.c:266 +0xb6
code.google.com/p/goprotobuf/proto.RegisterEnum(0x5777d0, 0x14, 0xc21009bd50, 0xc21009bd80)
    ~/work/go/src/code.google.com/p/goprotobuf/proto/properties.go:646 +0xd2
github.com/dancannon/gorethink/ql2.init·1()
    ~/work/go/src/github.com/dancannon/gorethink/ql2/ql2.pb.go:1023 +0x4e
github.com/dancannon/gorethink/ql2.init()
    ~/work/go/src/github.com/dancannon/gorethink/ql2/ql2.pb.go:1029 +0x71c
github.com/dancannon/gorethink.init()
    ~/work/go/src/github.com/dancannon/gorethink/utils.go:168 +0x80

**Comment by wildattire** [comment]
As it turns out this is the result of the simultaneous use of rethinkgo and gorethink.
